name: "📍 Pointage"

on:
  schedule:
    - cron: "30 3,7,11,15,19,23 * * *"
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FILE_NAME1: data_$(date +'%Y%m%d')
  FILE_NAME2: pointages_$(date +'%Y%m%d')
  FILE_NAME3: trajectoire_$(date +'%Y%m%d')

permissions:
  contents: write
  id-token: write

jobs:
  generate:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.15

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          mkdir -p output
          python trajectoires_pointages.py --output-dir output

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-file
          path: output/*

  release:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: generated-file

      - name: Delete previous release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete latest --yes || echo "No previous release to delete"

      - name: Create new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv ${{ env.FILE_NAME1 }}.gpkg latest_data.gpkg
          mv ${{ env.FILE_NAME2 }}.geojson pointages.geojson
          mv ${{ env.FILE_NAME3 }}.geojson trajectoire.geojson
          gh release create latest latest_data.gpkg pointages.geojson trajectoire.geojson --title "Latest Data Daily Release" --notes "Automatically generated daily release"
